### PR TITLE
k8s, ci: bump centos stream at nodes

### PR DESCRIPTION
**Pull request by qinqon**
Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by cathay4t** [comment]
@qinqon The upgrade seems has dependency issue of docker, any reason we don't use podman?

**Comment by qinqon** [comment]
> @qinqon The upgrade seems has dependency issue of docker, any reason we don't use podman?

The kubevirtci is able to use podman https://github.com/kubevirt/kubevirtci/blob/main/PODMAN.md, let's give it a try.

**Comment by qinqon** [comment]
@cathay4t after upgrading the kubevirtci version (it's no longer using docker at nodes) k8s lane is working fine.

**Comment by qinqon** [comment]
@cathay4t is this ok now ?

**Review by cathay4t — APPROVED** [review]

**Pull request merged**
