### PR TITLE
nm, ovs: Fix report crash when OVS has dup iface names

### PR DESCRIPTION
**Pull request by EdDev**
In case of an existing OVS deployment which uses an identical name for
the bridge, port and interface, libnmstate.show() exploded.

It is now possible to report such deployments.

### CODE REVIEW

**Comment by ffmancera** [comment]
Please, let me prepare a full solution for this. Thanks!

**Comment by tyll** [comment]
> Please, let me prepare a full solution for this. Thanks!

A more comprehensive solution can still be added as a follow-up. IMHO it is important to ensure this is fixed on base before merging the PRs on the other branches.

**Comment by EdDev** [comment]
> > Please, let me prepare a full solution for this. Thanks!
> 
> A more comprehensive solution can still be added as a follow-up. IMHO it is important to ensure this is fixed on base before merging the PRs on the other branches.

I am not sure this is possible, the changes needed here are much different and the fixes I used on previous version are not enough, on base another layer fails. So there are two points that need caring here beyond what I just posted:
- Handle the new error seen here (coming from `register_async`).
- Support reporting duplicate names.

If we manage to fix the 1st now, great. If we cannot do it in a few days, I prefer the fixes on older branched to get in and work on this in parallel.

**Comment by cathay4t** [comment]
This PR does not works when ovs internal interface holding the same name with ovs bridge.

The upper level fix has been working at https://github.com/nmstate/nmstate/pull/1370

**Review by cathay4t — CHANGES_REQUESTED** [review]
In stead of filtering `ovs_ports_info`, we should not use interface name as search rule in `_get_port_profiles`.

I will try to work out a better approach.

**Comment by cathay4t** [comment]
Closed as dup of #1370

**Pull request closed without merging**
