### PR TITLE
Route-rule: Added route-rules list sorting by ip-address

### LINKED ISSUE #1416: Sort the route rule before showing via `nmstatectl` or `libnmstate.show()`
The route rule should be sorted in:
 * IPv6 is preferred than IPv4.
 * Smaller numbered priority is preferred than bigger number.

### PR DESCRIPTION
**Pull request by SudhanAruna**
Added sorting route rules by prioritizing ipv6 ip-address over ipv4 ip address.
Fix #1416 

Signed-off-by: Arunagirinadan Sudharshan <sudhan.aruna.97@gmail.com>

### CODE REVIEW

**Review by ffmancera — CHANGES_REQUESTED** [review]
Hi Aruna, this looks great! Could you add an integration tests?

This test should do:
1. Add two ipv4/ipv6 routes (not sorted).
2. Apply the state
3. Show the state and check the first route is ipv6 and second one is ipv4.

In addition, could you add more information about how the routes are being sorted? It would be nice to have detailed information about the criteria on the commit message.

Thank you!

**Comment by SudhanAruna** [comment]
> Hi Aruna, this looks great! Could you add an integration tests?
> 
> This test should do:
> 
> 1. Add two ipv4/ipv6 routes (not sorted).
> 2. Apply the state
> 3. Show the state and check the first route is ipv6 and second one is ipv4.
> 
> In addition, could you add more information about how the routes are being sorted? It would be nice to have detailed information about the criteria on the commit message.
> 
> Thank you!

@ffmancera Sure, I'll include those.

**Review by cathay4t — CHANGES_REQUESTED** [review]
Similar to `RouteEntry`, could you implement `__lt__()` for `RouteRuleEntry`?
So you don't have to put sorting coding in `nmstate.py` but keep the code in `route_rule.py`.

**Comment by SudhanAruna** [comment]
> Similar to `RouteEntry`, could you implement `__lt__()` for `RouteRuleEntry`?
> So you don't have to put sorting coding in `nmstate.py` but keep the code in `route_rule.py`.

@cathay4t Sure, working on it

**Comment by ffmancera** [comment]
> > Similar to `RouteEntry`, could you implement `__lt__()` for `RouteRuleEntry`?
> > So you don't have to put sorting coding in `nmstate.py` but keep the code in `route_rule.py`.
> 
> @cathay4t Sure, working on it

Hello! How is this going? There is no hurry I just wanted to check out if you need any help :-)

Thanks!

**Comment by SudhanAruna** [comment]
> > > Similar to `RouteEntry`, could you implement `__lt__()` for `RouteRuleEntry`?
> > > So you don't have to put sorting coding in `nmstate.py` but keep the code in `route_rule.py`.
> > 
> > 
> > @cathay4t Sure, working on it
> 
> Hello! How is this going? There is no hurry I just wanted to check out if you need any help :-)
> 
> Thanks!
Hi,
Sorry I couldn't work on the requested changes. I'll update you by this weekend.

**Pull request closed without merging**
