### PR TITLE
Mock rebase

### PR DESCRIPTION
**Pull request by tyll**
This contains the changes to the tests from #19 to rescue the changes and get them merged. The changes for the actual IP support need to be rebased on #20

### CODE REVIEW

**Comment by tyll** [comment]
@phoracek do you know what I need to do to fix tox in travis? It works locally.

**Comment by tyll** [comment]
@EdDev do you still want to re-use something from these changes? It conflicts now.

**Comment by EdDev** [comment]
I have refactored the whole thing and used the mock package instead.
There are no self created mock objects at the moment.

We do not need these, but it will be great if you can review the new stuff, sorry I merge it without a proper review cycle.

**Comment by tyll** [comment]
handled in #34 and #35

**Pull request closed without merging**
