### PR TITLE
README: Remove IRC channel

### PR DESCRIPTION
**Pull request by tyll**
Most questions on IRC are ignored, therefore it does not make sense to mention it in the README.

### CODE REVIEW

**Comment by ffmancera** [comment]
The questions are not ignored. There can be situations when no one is present when the question is asked.

I do not see the value of removing this from the README.

**Comment by tyll** [comment]
This year, I see 7 topics raised by contributors, only two were responded to. There is no development discussion otherwise, for example between you, Gris and Wen so pointing people in the README to a mostly non-functional IRC channel is not very helpful. Removing the IRC channel (and decommissioning it) will avoid that people join there unnecessarily.

**Comment by ffmancera** [comment]
@cathay4t what is your opinion?

**Comment by cathay4t** [comment]
I prefer removing IRC from README.

**Review by ffmancera — APPROVED** [review]

**Pull request merged**
