### PR TITLE
Backport container and travis changes.

### PR DESCRIPTION
**Pull request by ffmancera**
This is backporting: #894 and #887

### CODE REVIEW

**Comment by ffmancera** [comment]
Rebased! Thanks!

**Comment by tyll** [comment]
It does not seem to rebuild the container image locally even though /packaging changed, seems like a bug.

**Comment by ffmancera** [comment]
> It does not seem to rebuild the container image locally even though /packaging changed, seems like a bug.

Debugging.

**Comment by ffmancera** [comment]
@tyll, Thanks! I fixed it. It was failing because I forgot to add the nmstate-0.2 tag in one place. Thanks!

**Comment by tyll** [comment]
> @tyll, Thanks! I fixed it. It was failing because I forgot to add the nmstate-0.2 tag in one place. Thanks!

The log message for building says:

```
Building '/home/travis/build/nmstate/nmstate/packaging/Dockerfile.centos8-nmstate-dev' into tag 'quay.io/nmstate/centos8-nmstate-dev'...
```
And it is building the image and afterwards downloading it to run the test. I think the message should probably also use the nmstate-0.2 tag.

**Comment by ffmancera** [comment]
> > @tyll, Thanks! I fixed it. It was failing because I forgot to add the nmstate-0.2 tag in one place. Thanks!
> 
> The log message for building says:
> 
> ```
> Building '/home/travis/build/nmstate/nmstate/packaging/Dockerfile.centos8-nmstate-dev' into tag 'quay.io/nmstate/centos8-nmstate-dev'...
> ```
> 
> And it is building the image and afterwards downloading it to run the test. I think the message should probably also use the nmstate-0.2 tag.

Fixed. Is now using the nmstate-0.2 tag.

**Comment by ffmancera** [comment]
> Please change back to docker.io. as quay.io is cache the build.

Done! Thanks.

**Pull request merged**
