### PR TITLE
Test: Enable nmstate CentOS CI

### PR DESCRIPTION
**Pull request by liangwen12year**
Signed-off-by: Wen Liang <liangwen12year@gmail.com>

### CODE REVIEW

**Comment by vbenes** [comment]
retest

**Comment by vbenes** [comment]
retest

**Comment by vbenes** [comment]
retest

**Comment by liangwen12year** [comment]
retest

**Comment by vbenes** [comment]
retest

**Comment by liangwen12year** [comment]
retest

**Comment by vbenes** [comment]
retest

**Comment by liangwen12year** [comment]
retest

**Comment by vbenes** [comment]
retest

**Pull request closed without merging**
