### PR TITLE
Demo: using natural language to generate nmstate YAML for linux bridge

### PR DESCRIPTION
**Pull request by elomscansio**
Still trying to know how this nlp things work.

### CODE REVIEW

**Comment by elomscansio** [comment]
See
fn test_nlpm: https://github.com/elomscansio/nmstate/blob/d27dd2ddc553e241f17f1350fdfb6f5c7171032e/rust/src/lib/unit_tests/nlpm.rs#L4

fn nlpm: https://github.com/elomscansio/nmstate/blob/d27dd2ddc553e241f17f1350fdfb6f5c7171032e/rust/src/lib/nlpm.rs#L10

print:  https://pastebin.com/ENXNYiEs

**Comment by elomscansio** [comment]
Concerning the bad code structure, this is just a demo so i'm still test running stuff

**Comment by elomscansio** [comment]
Hello, @ffmancera @cathay4t @ihuguet I'm currently waiting for your responses to proceed with the [PR](https://github.com/nmstate/nmstate/pull/2647). For example, after extracting the required details with NLP, should I create a NetworkState instance, or is it preferable to return static YAML with placeholders for the extracted information such as port, bridge, and so on?

**Comment by cathay4t** [comment]
Since this is demo, you have to evaluate whether using struct is better than yaml. Both of them are API, hence I have no preference.

**Comment by ffmancera** [comment]
As the contribution period finished, we are closing this. There is no intention to merge this because it was just a demo.

**Pull request closed without merging**
