### PR TITLE
nmstatectl: Convert --only to an argument

### PR DESCRIPTION
**Pull request by tyll**
This changes
nmstatectl show --only eth0
to
nmstatectl show eth0

This is another split from #73

### CODE REVIEW

**Comment by tyll** [comment]
What kind of interfaces can I expect in the integration test environment to be present? lo and eth0?

**Comment by EdDev** [comment]
Yes, lo and eth0 will appear. You can just run the docker locall and check it out. We need to add more ifaces for complex configs... on my todo.

**Comment by tyll** [comment]
ci test please

**Comment by tyll** [comment]
ci test please

**Pull request merged**
