### PR TITLE
rust: unify clib free functions

### PR DESCRIPTION
**Pull request by qinqon**
All the "free" functions are doing exactly the same and can be unify
into one.

### CODE REVIEW

**Comment by cathay4t** [comment]
Could you explain why we should break C API in this PR?

**Comment by qinqon** [comment]
> Could you explain why we should break C API in this PR?

We don't have to keep retrocompatibility yet right ? if this is the case I can put some wrapper functions to keep it.

The idea was that all the `free` functions do exactly the same, so one `free` functions is enough.

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
Yes. Remove duplicate code is one benefit.  Approved. Please rebase.

**Comment by qinqon** [comment]
> Yes. Remove duplicate code is one benefit. Approved. Please rebase.

Done

**Pull request merged**
