### PR TITLE
Remove Nmstate CI dependency on NetworkManager-config-server

### PR DESCRIPTION
**Pull request by liangwen12year**

### CODE REVIEW

**Comment by liangwen12year** [comment]
The patch is not ready for review.

**Comment by liangwen12year** [comment]
The tier2 failure seems to be the a bug in NM, even if the NM config has the setting - `no-auto-default=*`, after NM restart,  NM still create the default `Wired connection 1`, see

```
Nov 29 20:40:23 cd66f86b89b5 NetworkManager[19242]: <trace> [1701290423.8500] settings: auto-default: creating in-memory connection 4227a6ec-5433-3471-9ae8-46cc4f4bf61c (Wired connection 1) for device hosta_nic
Nov 29 20:40:23 cd66f86b89b5 NetworkManager[19242]: <trace> [1701290423.8503] keyfile: commit: 4227a6ec-5433-3471-9ae8-46cc4f4bf61c (Wired connection 1) added as "/run/NetworkManager/system-connections/Wired connection 1.nmconnection" (nm-generated)
Nov 29 20:40:23 cd66f86b89b5 NetworkManager[19242]: <trace> [1701290423.8505] settings: add-connection: successfully added connection 4227a6ec-5433-3471-9ae8-46cc4f4bf61c,'Wired connection 1' (00fd65144c04246a/keyfile, "/run/NetworkManager/system-connec
``` 
```
[root@cd66f86b89b5 nmstate-workspace]# nmcli c
NAME                UUID                                  TYPE      DEVICE    
Wired connection 1  4227a6ec-5433-3471-9ae8-46cc4f4bf61c  ethernet  hosta_nic 
```

**Review by cathay4t — APPROVED** [review]
LGTM

**Pull request merged**
