### PR TITLE
replace link in stale.yml with correct link

### LINKED ISSUE #1399: Replace existing reference to "master" in stale bot
https://github.com/nmstate/nmstate/blob/dbb712e53220768b01ffee2c121aa2679191aabe/.github/stale.yml#L11

This link must be replace with the correct one pointing to base branch instead of master branch.

### PR DESCRIPTION
**Pull request by shreyagupta30**
This fixes #1399 
I have replaced the link in state.yml. The new link points to the base branch now.

### CODE REVIEW

**Review by ffmancera — APPROVED** [review]
Thank you! It looks good, could you rebase it with the upstream repository? If you need any help, let me know :-)

**Comment by tyll** [comment]
Thanks, there is a typo in the commit message. It says `staTe.yml` but should say `staLe.yml` (using upper-case to highlight the problem).

**Comment by ffmancera** [comment]
> Thanks, there is a typo in the commit message. It says `staTe.yml` but should say `staLe.yml` (using upper-case to highlight the problem).

Oh thank you! I didn't notice that. Please, could you adjust it and rebase? @shreyagupta30

**Comment by shreyagupta30** [comment]
Hi, @tyll and @ffmancera I have made the required changes in the commit message. I still figuring out rebasing.

**Comment by shreyagupta30** [comment]
Hi, @ffmancera I have tried rebasing the PR with upstream. Could you please review it?

**Pull request merged**
