### PR TITLE
Support manual state verification

### PR DESCRIPTION
**Pull request by tyll**
To help other reviewer, below lines are added by @cathay4t:

This PR introduce a way to allow user commit or rollback a checkpoint manually.

API:
 * `libnmstate.netapplier.apply()` support new optional argument `commit=False`.
    If set, the function will return a checkpoint object. The checkpoint object could be used for
    `libnmstate.netapplier.commit()` or `libnmstate.netapplier.rollback()`

CLI:
 * `nmstatectl set <yaml_file> --no-commit` which will print a checkpoint dbus object path.
 *  `nmstatctl commit <checkpoint_dbus_obj_path>` or `nmstatctl rollback <checkpoint_dbus_obj_path>`

### CODE REVIEW

**Comment by tyll** [comment]
@cathay4t this is ready for review, integration tests are missing. I will add them if you like the overall approach and code.

**Comment by cathay4t** [comment]
If I do `nmstatectl commit` after the checkpoint timeout, I will got this long exception:

```
[fge@fed ~]$ sudo nmstatectl commit /org/freedesktop/NetworkManager/Checkpoint/7
Traceback (most recent call last):
  File "/home/fge/Source/nmstate/libnmstate/nm/checkpoint.py", line 125, in destroy
    self._manager.interface.CheckpointDestroy(self._dbuspath)
  File "/usr/lib64/python3.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.NetworkManager.InvalidArguments: checkpoint /org/freedesktop/NetworkManager/Checkpoint/7 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fge/Source/nmstate/libnmstate/netapplier.py", line 72, in commit
    nmcheckpoint.destroy()
  File "/home/fge/Source/nmstate/libnmstate/nm/checkpoint.py", line 127, in destroy
    raise NMCheckPointError(str(e))
libnmstate.nm.checkpoint.NMCheckPointError: org.freedesktop.NetworkManager.InvalidArguments: checkpoint /org/freedesktop/NetworkManager/Checkpoint/7 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fge/Source/nmstate/nmstatectl/nmstatectl.py", line 131, in commit
    netapplier.commit(args.checkpoint)
  File "/home/fge/Source/nmstate/libnmstate/netapplier.py", line 74, in commit
    raise NmstateValueError(str(e))
libnmstate.error.NmstateValueError: org.freedesktop.NetworkManager.InvalidArguments: checkpoint /org/freedesktop/NetworkManager/Checkpoint/7 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fge/Source/nmstate/nmstatectl/nmstatectl.py", line 58, in main
    return args.func(args)
  File "/home/fge/Source/nmstate/nmstatectl/nmstatectl.py", line 133, in commit
    print("ERROR committing change: {}".format(e.message))
AttributeError: 'NmstateValueError' object has no attribute 'message'
```

Similar error also happens when run `nmstatectl commit` as non-privileged user.

**Comment by tyll** [comment]
> Basically, I like the idea of manual checkpoint and it works well mostly.
> 
> Things to fix:
> 
> * `During handling of the above exception, another exception occurred:` issue on:
>   * No privileged.
>   * Create 2+ checkpoint.
>   * Commit or rollback after timeout.

These errors are fixed now.

> * Add integration test for nmstatectl to simulate the use of above cases.

WIP.

**Comment by cathay4t** [comment]
In stead of showing detail implementation, please consider this patch:

```patch
diff --git a/libnmstate/netapplier.py b/libnmstate/netapplier.py
index bb45441..59c3ace 100644
--- a/libnmstate/netapplier.py
+++ b/libnmstate/netapplier.py
@@ -124,8 +124,10 @@ def _apply_ifaces_state(desired_state, verify_change, commit,
                 _verify_change(desired_state)
         if not commit:
             return checkpoint
-    except nm.checkpoint.NMCheckPointCreationError:
-        raise NmstateConflictError('Error creating a check point')
+    except nm.checkpoint.NMCheckPointCreationError as e:
+        six.raise_from(
+            NmstateConflictError(
+                'Error creating a check point: {}'.format(str(e))), None)
 
 
 def _verify_change(desired_state):
diff --git a/libnmstate/nm/checkpoint.py b/libnmstate/nm/checkpoint.py
index 4b8211e..ddf0358 100644
--- a/libnmstate/nm/checkpoint.py
+++ b/libnmstate/nm/checkpoint.py
@@ -18,6 +18,7 @@
 import logging
 
 import dbus
+import six
 
 import libnmstate.nm.nmclient
 
@@ -118,7 +119,7 @@ class CheckPoint(object):
                           dbuspath, timeout)
             self._dbuspath = dbuspath
         except dbus.exceptions.DBusException as e:
-            raise NMCheckPointCreationError(str(e))
+            six.raise_from(NMCheckPointCreationError(str(e)), None)
 
     def destroy(self):
         try:
```

**Comment by tyll** [comment]
> In stead of showing detail implementation, please consider this patch:

Yes, I have considered it but I do not see why this would be an advantage. The implementation details are stored in the `__context__` attribute, therefore it is IMHO not part of an API. The default exception handler is just using it for a more useful traceback and the correct way is to handle the exception instead of making them less useful.

**Pull request merged**
