### PR TITLE
packaging: add NM 1.22-git container image to build_container.sh

### PR DESCRIPTION
**Pull request by ffmancera**
Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

### CODE REVIEW

**Comment by ffmancera** [comment]
Do not merge this.

**Comment by cathay4t** [comment]
@ffmancera  I have fixed the rpmdb issue at PR #813 please review.

**Comment by cathay4t** [comment]
We don't need this rebuild the git container anymore as we fixed the rpmdb corruption.

Use copr repo in .travis.yml is better.

**Comment by ffmancera** [comment]
> We don't need this rebuild the git container anymore as we fixed the rpmdb corruption.
> 
> Use copr repo in .travis.yml is better.

Thanks!

**Pull request closed without merging**
