### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jona42-ui**
slight spelling correction

### CODE REVIEW

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
@jona42-ui Thanks for the contribution. Could you run `git commit --amend --signoff` to add line like `Signed-off-by: Your  Name <you@email.address>` to the bottom of git commit message?

That's the reason DCO CI failed.

**Comment by jona42-ui** [comment]
does that suffice @cathay4t

**Comment by jona42-ui** [comment]
seems DCO CI is not triggered. do you need to re run it from your side

**Comment by ffmancera** [comment]
I triggered it :)

**Comment by ffmancera** [comment]
Hi, the main problem is that you created an extra empty commit. Instead, you should modify the initial one you created.

**Comment by ffmancera** [comment]
Thank you! The change looks good to me, let's wait for CI results!

**Comment by jona42-ui** [comment]
is there anything i am missing here? @cathay4t

**Comment by cathay4t** [comment]
No, rebase should get CI happy

**Comment by cathay4t** [comment]
Merged. Thanks!

**Pull request merged**
