### PR TITLE
Add --k8s option to run-tests.sh

### PR DESCRIPTION
**Pull request by qinqon**
Prow job to run this on CI https://github.com/kubevirt/project-infra/pull/1055

Result of the k8s prow lane https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/nmstate_nmstate/1539/pull-nmstate-k8s/1372567041684279296

Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by cathay4t** [comment]
@qinqon Hi Enrique, thanks for the effort. Is that any place I may check the test results of this k8s CI?

**Comment by qinqon** [comment]
@cathay4t I have a PR to add a job at kubevirt prow https://github.com/kubevirt/project-infra/pull/1055, I am running it manually, right now with the lat force-push it's running here, https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/nmstate_nmstate/1539/pull-nmstate-k8s/1374286117175562240.

After the job merged a kubevirt project-infra it will appear as another lane at nmstate PRs, it takes around 7 min so is not a pain.

Next step is to use the same but with openshift-ci.

**Review by cathay4t — APPROVED** [review]
LGTM even I don't know the k8s test could be showing in nmstate PR page.

**Review by ffmancera — APPROVED** [review]
The CI failures are not related to this PR. I am working on them, thanks!

**Pull request merged**
