### PR TITLE
Refactor testlib

### PR DESCRIPTION
**Pull request by EdDev**
Based on #93

### CODE REVIEW

**Comment by EdDev** [comment]
@tyll unless you have any objection, I will merge this one.

**Comment by tyll** [comment]
The description in the commit message should be in the imperative mood IMHO: https://en.wikipedia.org/wiki/Imperative_mood instead of using third person passive speech (see the example from @cathay4t)  - also it is `state-related functions` AFAIK (with a hyphen) because it is an adjective. But these are minor issues, so you can also merge if you prefer not to correct this. Please keep it in mind for the future, though. :-)

**Comment by EdDev** [comment]
How about now?

**Comment by tyll** [comment]
Correct IMHO would be 
```
Move the state-related logic from `testlib.assertlib` to
the new class `State` in `testlib.statelib`.
```
* Move instead of Moving (imperative mood is how you would command someone to do something)
* state-related instead of state related
* it is `the new class State` and not `a new class State` - `a new class named State` would also be possible (I also added backticks around State, since it is actually code AFAICS.

**Comment by EdDev** [comment]
Done

**Comment by EdDev** [comment]
ci test please

**Pull request merged**
