### PR TITLE
[nmstate-2.0] ovs, dpdk: add support to rx_queue parameter

### PR DESCRIPTION
**Pull request by ffmancera**
```
---
interfaces:
  - name: ovs-br0
    type: ovs-bridge
    state: up
    bridge:
      options:
        datapath: netdev
      port:
        - name: ovs0
  - name: ovs0
    type: ovs-interface
    state: up
    dpdk:
      devargs: "000:18:00.2"
      rx_queue: 1000
```

Integration test case added.

Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

### CODE REVIEW

**Review by cathay4t — APPROVED** [review]
Code looks good to me. Waiting server to try on real hardware.

**Review by cathay4t — CHANGES_REQUESTED** [review]
Please also bring the rust code in for this feature.

**Comment by ffmancera** [comment]
> Please also bring the rust code in for this feature.

Hi, considering this is Nmstate-2.0 I think the support in rust is not needed. Users would be able to use 2.1.0 or greater. In order to backport this patch to rust, the OVS DPDK implementation and many other patches would be required.

What do you think?

**Comment by cathay4t** [comment]
No need to touch rust code in nmstate-2.0 branch.

**Pull request merged**
