### PR TITLE
[nmstate-0.3] libnmstate-varlink: Implementing varlink support for libnmstate

### PR DESCRIPTION
**Pull request by qinqon**
Backport of https://github.com/nmstate/nmstate/commit/ecb2b8b3ec561eb05407a7e56931b6d17e848382

Implemented varlink support for libnmstate functions (show, apply, commit and rollback)
Added test cases for varlink service
Integrated with setup.py
Added README file

Signed-off-by: Arunagirinadan Sudharshan <sudhan.aruna.97@gmail.com>

### CODE REVIEW

**Review by ffmancera — CHANGES_REQUESTED** [review]
Hello! Thanks for working on this. I think https://github.com/nmstate/nmstate/commit/d50eb0055231ea5e72ac46e57f9fb146c644fd79 is missing here :-)

**Comment by qinqon** [comment]
@ffmancera included the man page commit.

**Review by ffmancera — COMMENTED** [review]
This looks good to me, I will try it out manually before merging :-)

**Review by ffmancera — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
