### PR TITLE
tox: Pin and update pytest* versions

### PR DESCRIPTION
**Pull request by EdDev**

### CODE REVIEW

**Comment by EdDev** [comment]
Why merge option is available?

**Comment by tyll** [comment]
> Why merge option is available?

why not?

**Comment by EdDev** [comment]
Only rebase should be available. Merging is hell.

**Comment by tyll** [comment]
> Only rebase should be available. Merging is hell.
> 
> Has anyone changed the rules?

I think you are just confused by the label, it is what you configured and want, since the PR is merged into master when you press the button without a merge commit.

**Comment by EdDev** [comment]
On the mobile it says `merge`, that confused me.

**Pull request merged**
