### PR TITLE
README: Add Copr GIT build status

### PR DESCRIPTION
**Pull request by tyll**
Signed-off-by: Till Maas <opensource@till.name>

### CODE REVIEW

**Comment by tyll** [comment]
The CI now shows a segfault (cc @thom311):

http://jenkins.ovirt.org/job/nmstate_nmstate_standard-check-pr/741/display/redirect

```
tests/integration/examples_test.py::test_add_remove_ovs_bridge /bin/bash: line 2:  2966 Segmentation fault      (core dumped) pytest --verbose --verbose --log-level=DEBUG --durations=5 --cov=/usr/lib/python2.7/site-packages/libnmstate --cov=/usr/lib/python2.7/site-packages/nmstatectl --cov-report=html:htmlcov-py27 tests/integration

```

**Comment by tyll** [comment]
This might be the relevant backtrace:
```
#1  0x00007f6d84f4ef96 in object_property_maybe_complete (self=0x1) at libnm/nm-object.c:450
        priv = <optimized out>
        self_keep_alive = <optimized out>
        i = <optimized out>
        iter = <optimized out>
        safe = <optimized out>
#2  0x00007f6d84f4f3c8 in init_finish (initable=<optimized out>, result=0x235bc30, error=0x0) at libnm/nm-object.c:1160
        odata = 0x319c490
        simple = 0x235bc30
        priv = 0x26738b0
#3  0x00007f6d84f336bb in obj_nm_inited (object=<optimized out>, result=<optimized out>, user_data=<optimized out>) at libnm/nm-client.c:2624
No locals.
#4  0x00007f6d87d20077 in g_simple_async_result_complete () from /lib64/libgio-2.0.so.0
No symbol table info available.
#5  0x00007f6d87d200d9 in complete_in_idle_cb () from /lib64/libgio-2.0.so.0
No symbol table info available.
#6  0x00007f6d88290c77 in g_idle_dispatch () from /lib64/libglib-2.0.so.0
No symbol table info available.

```

**Comment by cathay4t** [comment]
ci test please

**Comment by tyll** [comment]
ci test please

**Comment by cathay4t** [comment]
Merged. Thanks for the patch.

**Pull request merged**
