### PR TITLE
Integration tests: Set G_DEBUG=fatal-warnings

### PR DESCRIPTION
**Pull request by tyll**
Thomas Haller recommended this in #169

Signed-off-by: Till Maas <opensource@till.name>

### CODE REVIEW

**Comment by tyll** [comment]
@thom311 does this make warnings such as `(process:1274): libnm-WARNING **: no object known for /org/freedesktop/NetworkManager/ActiveConnection/89` fail? Is this a good idea?

@EdDev this shows some errors in the CI, not sure if they are related to this change or have a different cause since the libnm warning is shown after the test failed.

**Comment by thom311** [comment]
> @thom311 does this make warnings such as (process:1274): libnm-WARNING **: no object known for /org/freedesktop/NetworkManager/ActiveConnection/89 fail? Is this a good idea?

Hm, these are bugs in libnm. Optimally, you'd set G_DEBUG=fatal-warnings, but unless that is fixed, you cannot. Sorry.

**Comment by tyll** [comment]
@thom311 should we file a bug report for libnm? Is there any additional information that you need? A journal with NM trace log for this CI failure is available at https://jenkins.ovirt.org/job/nmstate_nmstate_standard-check-pr/550/artifact/check-patch.el7.x86_64/journal.log

**Comment by thom311** [comment]
Not necessary. These failures are known and easy to reproduce. Need to be fixed eventually, but we didn't get to it yet.

**Comment by thom311** [comment]
> Not necessary. These failures are known and easy to reproduce. Need to be fixed eventually, but we didn't get to it yet.

@tyll I changed my mind :) Could you please open a bug, with the error message to track it. The message alone should suffice, and a short description what you were doing. Also, as this happens in a fairly automated test setup, please remember (take note) how to reproduce this later. Thanks.

**Comment by tyll** [comment]
> @tyll I changed my mind :) Could you please open a bug, with the error message to track it. The message alone should suffice, and a short description what you were doing. Also, as this happens in a fairly automated test setup, please remember (take note) how to reproduce this later. Thanks.

Reprted in https://bugzilla.redhat.com/show_bug.cgi?id=1655783

**Comment by tyll** [comment]
Created internal tracker to revisit this https://nmstate.atlassian.net/browse/NMSTATE-83 once it is fixed in libnm.

**Pull request closed without merging**
