### PR TITLE
nmstatectl: filter route rule against auto-route-table-id

### LINKED ISSUE #1153: `nmstatectl show <nic_name>` should match route rule against `auto-route-table-id` also.
When certain interface been configure with `auto-route-table-id`, the `nmstatectl show <nic_name>` should include a route  rule
targeting this route table also.

### PR DESCRIPTION
**Pull request by Razaloc**
Signed-off-by: Rafael G. Ruiz <llerrak@hotmail.com>

### CODE REVIEW

**Comment by cathay4t** [comment]
@Razaloc Can we postpone this PR for a week or so.

Currently nmstate still have issue on setting route rule to `auto-route-table-id`. So I cannot tell whether your PR works or not.

**Comment by cathay4t** [comment]
@ffmancera 

Since you was working on the `auto-route-table-id`. Can you fix the issue when applying this state?

```yml
---
route-rules:
  config:
    - ip-from: 192.168.3.2/32
      route-table: 200
    - ip-from: 2001:db8:b::/64
      route-table: 200
interfaces:
  - name: dhcpcli
    type: ethernet
    state: up
    mtu: 1500
    ipv4:
      enabled: true
      dhcp: true
      auto-route-table-id: 200
```

Thank you.

**Comment by ffmancera** [comment]
> @ffmancera
> 
> Since you was working on the `auto-route-table-id`. Can you fix the issue when applying this state?
> 
> ```yaml
> ---
> route-rules:
>   config:
>     - ip-from: 192.168.3.2/32
>       route-table: 200
>     - ip-from: 2001:db8:b::/64
>       route-table: 200
> interfaces:
>   - name: dhcpcli
>     type: ethernet
>     state: up
>     mtu: 1500
>     ipv4:
>       enabled: true
>       dhcp: true
>       auto-route-table-id: 200
> ```
> 
> Thank you.

Oh that is too bad. Yes, I will do it. Thanks!

**Comment by ffmancera** [comment]
I've tested this with #1293 and it is working. Logs:

```bash
[root@f3189e61ba03 nmstate-workspace]# nmstatectl show eth1
2020-08-22 10:55:03,821 root         DEBUG    Async action: Retrieve applied config: eth1 started
2020-08-22 10:55:03,823 root         DEBUG    Async action: Retrieve applied config: eth1 finished
---
dns-resolver:
  config: {}
  running: {}
route-rules:
  config:
  - ip-from: 192.168.3.2/32
    priority: 30000
    route-table: 200
routes:
  config: []
  running:
  - destination: fe80::/64
    metric: 100
    next-hop-address: ''
    next-hop-interface: eth1
    table-id: 254
  - destination: fe80::c8a0:fbff:fe81:1fa4/128
    metric: 0
    next-hop-address: ''
    next-hop-interface: eth1
    table-id: 255
  - destination: ff00::/8
    metric: 256
    next-hop-address: ''
    next-hop-interface: eth1
    table-id: 255
interfaces:
- name: eth1
  type: ethernet
  state: up
  ipv4:
    enabled: true
    address: []
    auto-dns: true
    auto-gateway: true
    auto-route-table-id: 200
    auto-routes: true
    dhcp: true
  ipv6:
    enabled: true
    address:
    - ip: fe80::c8a0:fbff:fe81:1fa4
      prefix-length: 64
    autoconf: false
    dhcp: false
  lldp:
    enabled: false
  mac-address: CA:A0:FB:81:1F:A4
  mtu: 1500
```

```bash
[root@f3189e61ba03 nmstate-workspace]# nmstatectl show eth0
2020-08-22 10:55:31,861 root         DEBUG    Async action: Retrieve applied config: eth1 started
2020-08-22 10:55:31,863 root         DEBUG    Async action: Retrieve applied config: eth1 finished
---
dns-resolver:
  config: {}
  running: {}
route-rules:
  config: []
routes:
  config: []
  running: []
interfaces:
- name: eth0
  type: ethernet
  state: up
  ipv4:
    enabled: true
    address:
    - ip: 10.88.3.246
      prefix-length: 16
  ipv6:
    enabled: true
    address:
    - ip: fe80::dcde:f0ff:fe5e:b7c7
      prefix-length: 64
  mac-address: DE:DE:F0:5E:B7:C7
  mtu: 1500
```

**Review by ffmancera — APPROVED** [review]
It looks good to me, waiting for #1293

**Review by cathay4t — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
