### PR TITLE
rust: Implement logger for dynamic lib

### PR DESCRIPTION
**Pull request by qinqon**
Implement an in memory logger for the rust clib that can dump the logs
until a certain point to a CString.

Based on https://docs.rs/memory_logger/latest/memory_logger/

### CODE REVIEW

**Comment by qinqon** [comment]
The  `log`  function from Loggger is not called, something is wrong at `setup`.

**Comment by cathay4t** [comment]
@qinqon I would like to take over this week as it is important for us to get logging in python CI test.

**Comment by qinqon** [comment]
> @qinqon I would like to take over this week as it is important for us to get logging in python CI test.

The main problem we have is that the retrieved logs are the logs from all the functions, we need a feature to mark the scope of the logs to be the function we are calling, I remember the tokio logger library is able to do it.

https://github.com/tokio-rs/tracing

**Comment by cathay4t** [comment]
Closing as duplicate of https://github.com/nmstate/nmstate/pull/1910

**Pull request closed without merging**
