### PR TITLE
schema: Add LLDP information

### PR DESCRIPTION
**Pull request by EdDev**

### CODE REVIEW

**Comment by tyll** [comment]
One idea I had, does it make sense to put the lldp schema in it's own file?

**Comment by tyll** [comment]
@EdDev  Can this be closed for now?

**Comment by EdDev** [comment]
@tyll , it is still relevant. We need to support it, although it has lower priority for now.

**Comment by EdDev** [comment]
We will revisit it later on, closing it for now.

**Comment by tyll** [comment]
related #64

**Pull request closed without merging**
