### PR TITLE
Rust crate documentation

### LINKED ISSUE #2593: Documentation for Rust is not mention in README
In the documentation section at https://github.com/nmstate/nmstate/blob/base/README.md#documentation the Rust crate documentation is missing. We should add it.

You can find the rust crate docs here: https://docs.rs/nmstate/latest/nmstate/index.html

### PR DESCRIPTION
**Pull request by beekaz**
Add link to Rust crate documentation in the README

### CODE REVIEW

**Comment by ffmancera** [comment]
Hi! The change LGTM! But could you adjust some things before merging it?

* The commit message must be more descriptive.. something like this `README: add Rust crate documentation link`
* The commit needs to be signed-off. In order to do that to your current commit please do `git commit -s --amend`

Thank you!

**Review by beekaz — COMMENTED** [review]
Thanks for the review! I've addressed the feedback and updated the commit message to be more descriptive . I've also amended the commit to be signed-off.

The pull request is now ready for merging. Thanks!

**Comment by ffmancera** [comment]
> Thanks for the review! I've addressed the feedback and updated the commit message to be more descriptive . I've also amended the commit to be signed-off.
> 
> The pull request is now ready for merging. Thanks!

Hi! The commit is signed-off but the message didn't change.. could you check it out?

**Review by beekaz — COMMENTED** [review]
I have tried changing the commit description, yest its not reflecting, i didnt `git commit --amend` then edited it and did `git push`

**Comment by ffmancera** [comment]
> I have tried changing the commit description, yest its not reflecting, i didnt `git commit --amend` then edited it and did `git push`

You probably need to do `git push --force` as you are rewriting the git history.

**Comment by beekaz** [comment]
Thank you so  much it worked it !  I actually did `git push -f origin  <name of the branch>`, so this command isnt same as git push --force?

**Review by cathay4t — APPROVED** [review]
LGTM.

**Pull request merged**
