### PR TITLE
automation: Enable no-auto-default on all devices

### PR DESCRIPTION
**Pull request by EdDev**
Do not create generated connections automatically on all devices in the
test env.

This configuration has been re-introduced due to:
https://bugzilla.redhat.com/1687937

### CODE REVIEW

**Comment by tyll** [comment]
You need to change it for the CentOS file as well: https://github.com/nmstate/nmstate/blob/master/packaging/docker_sys_config.sh

**Comment by EdDev** [comment]
> You need to change it for the CentOS file as well

Done

**Comment by EdDev** [comment]
ci test please

**Comment by tyll** [comment]
There is still a failure in travis - is it expected?

**Comment by EdDev** [comment]
> There is still a failure in travis - is it expected?

Seems like a different problem: You can see that on exit, there is no auto profile in the list.

**Pull request merged**
