### PR TITLE
add project logo

### PR DESCRIPTION
**Pull request by phoracek**
Huge kudos to Mary Shakshober who was kind enough to create this great
logo for us. Thanks a lot.

Signed-off-by: Petr Horacek <phoracek@redhat.com>

### CODE REVIEW

**Comment by ffmancera** [comment]
Hi Thanks very much for this. We are waiting until September for everyone coming back from holidays in order to send a public vote. Sorry for the delay on this, we all appreciate this contribution very much!

**Comment by phoracek** [comment]
Fair enough :) Thanks for the response.

**Comment by cathay4t** [comment]
We have renamed the `master` branch to `base`. Please close this PR and create new one targeting the `base` branch.

Sorry for the troubles .

**Comment by phoracek** [comment]
Ack, thanks @cathay4t

**Pull request closed without merging**
