### PR TITLE
Fix typo at installing the libvarlink-util package

### PR DESCRIPTION
**Pull request by qinqon**

### CODE REVIEW

**Review by cathay4t — APPROVED** [review]
Thanks. LGTM.

**Comment by cathay4t** [comment]
@qinqon Please use `git commit --signoff --amend` to sign our commit. Thanks.

**Comment by ffmancera** [comment]
Please, sign the commit using `-s`. Thanks!

**Comment by qinqon** [comment]
@ffmancera this PR was created directly from github that's why It didn't have the signing.

**Pull request merged**
