### PR TITLE
libnmstate-varlink: Implementing varlink support for libnmstate

### PR DESCRIPTION
**Pull request by qinqon**
Backport from https://github.com/nmstate/nmstate/pull/1270

Implemented varlink support for libnmstate functions (show, apply, commit and rollback)
Added test cases for varlink service
Integrated with setup.py
Added README file

Signed-off-by: Arunagirinadan Sudharshan <sudhan.aruna.97@gmail.com>

### CODE REVIEW

**Comment by ffmancera** [comment]
Thanks for the contribution, why is this needed? Backporting varlink support will require a great effort. Thanks!

**Comment by qinqon** [comment]
We (kubernetes-nmstate) were investigating ways to keep nmstate alive while running commands since it affect CPU load starting it up everytime, so one option is to use varlink but we are at nmstate 0.2 and we cannot upgrade since nm at nodes is old, so I did try a backport to check how difficult would be.

**Comment by ffmancera** [comment]
> We (kubernetes-nmstate) were investigating ways to keep nmstate alive while running commands since it affect CPU load starting it up everytime, so one option is to use varlink but we are at nmstate 0.2 and we cannot upgrade since nm at nodes is old, so I did try a backport to check how difficult would be.

I think I could help you a little bit with this. Let me ask to the team about what do they think on backporting this. The ideal solution would be to upgrade to 0.4 or 0.3 at least. Thanks!

**Comment by qinqon** [comment]
@ffmancera I don't see varlink here https://github.com/nmstate/nmstate/tree/nmstate-0.3/nmstatectl, maybe is easier to backport to 0.3 ? also I doubt we are going to be able to have new nmstate 0.2 on time for us, so maybe a backport to 0.3 is more feasible so for us.

**Comment by qinqon** [comment]
Going to try to backport it to nmstate 0.3

**Pull request closed without merging**
