### PR TITLE
Integrate CentOS-stream into CI

### LINKED ISSUE #1028: Integrate CentOS-stream into CI
CentOS-stream now provides a newer NetworkManager version. Therefore it makes sense to include it in the CI.

### PR DESCRIPTION
**Pull request by adwait-thattey**
resolves #1028

### CODE REVIEW

**Comment by adwait-thattey** [comment]
@tyll I have added the Dockerfile for centos-stream

Apart from a bunch of lines at the start, rest code is same as the Dockerfile for CentOS8

**Comment by adwait-thattey** [comment]
@tyll 
The next step would be to add the test for this image in .travis.yml
But this image does not yet exist on docker hub

So how do I add in that?

Also how to add this in automation module so that this test will also run when running using `./run-tests`

**Comment by ffmancera** [comment]
> @tyll
> The next step would be to add the test for this image in .travis.yml
> But this image does not yet exist on docker hub
> 
> So how do I add in that?
> 
> Also how to add this in automation module so that this test will also run when running using `./run-tests`
> Thanks

I think you will need to do it in different PRs. You cannot add the image to dockerhub so IMO, we should merge this first and then add the test to travis CI in another PR. In addition, the following PR should also include changes to run-tests.sh in order to allow us to use that container when running the tests locally. I will review this later. Thanks for you patch!

**Comment by adwait-thattey** [comment]
@ffmancera Okay. I will wait till this is merged.
Thanks

**Comment by adwait-thattey** [comment]
Unmarked as WIP
Any changes required in this?

**Comment by tyll** [comment]
> I think you will need to do it in different PRs. You cannot add the image to dockerhub so IMO, we should merge this first and then add the test to travis CI in another PR. In addition, the following PR should also include changes to run-tests.sh in order to allow us to use that container when running the tests locally. I will review this later. Thanks for you patch!

Actually, the CI script should build the container locally if something is changed. So it should be possible to submit all changes in one PR.

Nevertheless, it should be added to `packaging/build-container.sh` at least and possibly other places as necessary.

**Comment by adwait-thattey** [comment]
@tyll I see. Thanks. I will try it tomorrow.

**Comment by adwait-thattey** [comment]
@cathay4t Thanks a lot. I was learning Travis and thought just including at one place will do.

**Comment by adwait-thattey** [comment]
The tests are failing because it's not able to pull the container. What to do?

**Comment by tyll** [comment]
> The tests are failing because it's not able to pull the container. What to do?

Looks like https://github.com/nmstate/nmstate/blob/master/automation/run-tests.sh#L228 hardcodes the image names and needs to be adjusted. You could add the new name or try to make it generic by computing the container spec (dockerfile) name from the container image.

**Comment by adwait-thattey** [comment]
It's now failing with
`NetworkManager-libnm >= 1:1.22.10 is needed by python3-libnmstate-0.3.1-0.20200508.52gitf2f9646.el8.noarch`

AFAIU it's defined in packaging/nmstate.spec
Should I modify it?

**Comment by tyll** [comment]
> @tyll It's now failing with
> `NetworkManager-libnm >= 1:1.22.10 is needed by python3-libnmstate-0.3.1-0.20200508.52gitf2f9646.el8.noarch`
> 
> AFAIU it's defined in packaging/nmstate.spec
> Should I modify it?

Please provide a link to the log with the error message. This makes it easier to follow-up.

**Comment by adwait-thattey** [comment]
Snippet which fails: https://pastebin.com/sggmzTmp
Full Log: https://api.travis-ci.com/v3/job/330035184/log.txt

**Comment by adwait-thattey** [comment]
I think it's failing because centos-stream ships with NetworkManager 1.22.8
But the check enforces 1.22.10

**Comment by tyll** [comment]
@ffmancera @ffmancera @EdDev what do you prefer? The next CentOS stream update willl probably contain 1.25.0, so it would be safe to enable the 1.22 copr for centos stream for now, to satisfy this.

**Comment by ffmancera** [comment]
> @ffmancera @ffmancera @EdDev what do you prefer? The next CentOS stream update willl probably contain 1.25.0, so it would be safe to enable the 1.22 copr for centos stream for now, to satisfy this.

IMO, yes. It should use 1.22 copr repo for centos stream. I will edit the copr repository. Thanks!

**Comment by adwait-thattey** [comment]
@tyll @ffmancera Sorry I am a bit confused.
Wasn't the aim here to test for a different version of NM (1.22.8) that is included in centos-stream.
afaiu 1.22.10 (from the copr repo) is already being checked in centos8 script right?

**Comment by tyll** [comment]
> @tyll @ffmancera Sorry I am a bit confused.
> Wasn't the aim to test for a different version of NM (1.22.8) that is included in centos-stream.
> afaiu 1.22.10 (from the copr repo) is already being checked in centos8 script right?

We are expecting that the NetworkManager package in CentOS stream will be updated to 1.25.0 or later within the next weeks or month. Therefore this PR prepares for when this is done. If you like, you can also check how to adjust the dependency only for RHEL builds in the spec. Without spending too much time on it, it seems to be rather complicated but it is also a learning opportunity for RPM packaging. Hope this helps you.

**Comment by adwait-thattey** [comment]
Thanks
I will look into it.

**Comment by ffmancera** [comment]
I found an incompatibility in spec file of NetworkManager. I will fix it and update the Copr.

**Comment by ffmancera** [comment]
The buiding is failing [1] because specfile format in fedora rawhide has been updated. It is now fixed on nm-1-22 but not included in a release. I will enable centos-stream in NetworkManager-1.22-git in order to workaround this. Thanks!

**Comment by ffmancera** [comment]
@adwait-thattey Please use the following Copr repository in the centos-stream container in order to install NM-1.22 https://copr.fedorainfracloud.org/coprs/networkmanager/NetworkManager-1.22-git/

**Comment by adwait-thattey** [comment]
I have used the Copr repo
integ_tier2 test on centos-stream is failing 
https://travis-ci.com/github/nmstate/nmstate/jobs/350439703#L2456

**Comment by cathay4t** [comment]
> I have used the Copr repo
> integ_tier2 test on centos-stream is failing
> https://travis-ci.com/github/nmstate/nmstate/jobs/350439703#L2456

You need to include `tcpreplay` in the docker file as others did.

**Comment by adwait-thattey** [comment]
Now the `iface_admin_state_test` is failing. 
https://travis-ci.com/github/nmstate/nmstate/jobs/355035642#L2305

**Comment by cathay4t** [comment]
> Now the `iface_admin_state_test` is failing in centos-stream container.
> https://travis-ci.com/github/nmstate/nmstate/jobs/355035642#L2305

Please rebase and try again.

**Comment by cathay4t** [comment]
Merged. Thanks.

**Pull request merged**
