### PR TITLE
Packaging: Require PyGObject via requirements.txt

### LINKED ISSUE #184: PyGobject should be listed in requirements.txt
This requires changes to `tox.ini` and Travis-CI configuration.

### PR DESCRIPTION
**Pull request by tyll**
Signed-off-by: Till Maas <opensource@till.name>

This fixes #184 

@cathay4t you mentioned that the travis config might need to be adjusted as well, does it really?

### CODE REVIEW

**Comment by tyll** [comment]
Ah, travis broke and told me what is needed. Adjusted.

**Comment by cathay4t** [comment]
@tyll In order to use `apt`, you need to change to something like:

```yaml
sudo: required
language: c
addons:
  apt:
    packages:
    - python3-gi
    - etc
script:
  - tox
```

**Comment by tyll** [comment]
It seems that the gobject-retrospection package in ubuntu is too old to build pygobject.

**Comment by cathay4t** [comment]
@tyll Can you wait a while on this thing? Let me try whether we can use docker in travis for both
integration test and tox.

**Comment by tyll** [comment]
> @tyll Can you wait a while on this thing? Let me try whether we can use docker in travis for both
> integration test and tox.

Sure, I just stumbled upon this when trying to sync the spec files. Too bad that Travis makes this so hard.

**Pull request closed without merging**
