### PR TITLE
Create alias for nmstatectl subcommands

### PR DESCRIPTION
**Pull request by elomscansio**
Added aliases for commonly used nmstatectl subcommands to enhance usability and streamline command execution.

### CODE REVIEW

**Comment by ihuguet** [comment]
It doesn't look bad, but you've changed the formatting of the whole file. Please apply only the parts that need to be changed.

**Comment by elomscansio** [comment]
> It doesn't look bad, but you've changed the formatting of the whole file. Please apply only the parts that need to be changed.

I run `cargo fmt` since Rust formatting is checked by `cargo fmt` during CI runs.

**Comment by ihuguet** [comment]
> I run `cargo fmt` since Rust formatting is checked by `cargo fmt` during CI runs.

We all run it and it doesn't change the file. Has you deleted your `rust/.rustfmt.toml` file?

**Comment by elomscansio** [comment]
> > I run `cargo fmt` since Rust formatting is checked by `cargo fmt` during CI runs.
> 
> We all run it and it doesn't change the file. Has you deleted your `rust/.rustfmt.toml` file?

I run `cargo fmt` before committing the changes. I still have `rust/.rustfmt.toml` https://github.com/elomscansio/nmstate/blob/update/nmstate_subcommand_alias/rust/.rustfmt.toml#L1 but rust_lint ci job failed in my previous commits though.

**Comment by ihuguet** [comment]
I don't know what happens, I would say that you are applying a different formatting style. If I run `cargo fmt` or `rustfmt src/cli/ncl.rs` nothing changes for me. On the other side, `rust_lint` is not complaining on this PR with all the changes, so I'm confused.

**Comment by elomscansio** [comment]
> I don't know what happens, I would say that you are applying a different formatting style. If I run `cargo fmt` or `rustfmt src/cli/ncl.rs` nothing changes for me. On the other side, `rust_lint` is not complaining on this PR with all the changes, so I'm confused.

It was actually failing not after I run `cargo fmt` and force push

**Comment by ffmancera** [comment]
Thank you for your contribution, we are closing this in favor of https://github.com/nmstate/nmstate/pull/2633. Thanks.

**Pull request closed without merging**
