### PR TITLE
Added logs for failures details

### LINKED ISSUE #866: Save log to file in Travis
When a job in Travis fails, the logs are uploaded for later inspection. This lacks the pytest logs.

Task: Adjust pytest to also log to a file and ensure that the file will be uploaded on failure. This probably needs a `--log-file` for pytest in run-tests.sh that stores the logfile in the directory that is uploaded to the log storage server. Ideally, this would also include some machine-readable log, there might be some JSON output available.

### PR DESCRIPTION
**Pull request by biswajitpatra**
resolved #866 
failures.log will store all the details of failed test cases

### CODE REVIEW

**Comment by tyll** [comment]
Thank you. Did you try to add `--log-file` to the pytest commandline? Doesn't that suffice?

**Comment by biswajitpatra** [comment]
Yeh, I tried that, but all the details of failures were not stored.

**Comment by ffmancera** [comment]
Thank you for your contribution. I have a few comments:
- Please, could you provide the difference between using `--log-file` and your approach?
- In addition, please run `run-tests.sh`, please see the README.md in automation/ folder. All the tests must pass locally.
- Note that the DCO bot is checking the signature in the commit. Please use `git commit -s` when creating the commit to avoid this. 
- The `Merge branch` commit is not needed. In order to solve this I recommend you to rebase when pulling from upstream mazter. If you have git questions, a good book to learn from is [Pro git](https://git-scm.com/book/en/v2)

If you have any questions, please let me know. Thanks! :-)

**Comment by biswajitpatra** [comment]
All the test cases locally passes.

**Comment by EdDev** [comment]
>> Did you try to add --log-file to the pytest commandline? Doesn't that suffice?

> Yeh, I tried that, but all the details of failures were not stored.

Have you used ‘--log-file-level’ to set the log level to ‘DEBUG’?

**Pull request closed without merging**
