### PR TITLE
infrastructure: Setup bors

### PR DESCRIPTION
**Pull request by tyll**
Try to setup bors according to: https://github.com/bors-ng/bors-ng

Signed-off-by: Till Maas <opensource@till.name>

### CODE REVIEW

**Comment by tyll** [comment]
This will hopefully allow a bot to rebase/merge PRs after we reviewed them. It will only merge the PRs if the configured automated checks pass. But I am not sure if everything is setup to trigger these checks for bors...

**Comment by EdDev** [comment]
A robot cannot merge, only a maintainer should. By merging a maintainer publicly accepts the change and is willing to support it.
A review ack is not enough, the responsibility of pressing 'rebase/merge' exist.

**Comment by tyll** [comment]
The robot only does the technical steps to merge, i.e. rebase if necessary or bundling multiple approved PRs and run the test suite before merging into master. It still needs a command (bors r+) from a maintainer to start this work which is the same as pressing the button.

**Comment by tyll** [comment]
It seems that pytest_cov is currently broken in travis. Not sure why...

**Comment by cathay4t** [comment]
I don't trust robot to mess git merge/rebase things.

**Pull request closed without merging**
