### PR TITLE
WIP: Update asynchronous state retrieval

### PR DESCRIPTION
**Pull request by jona42-ui**
Previously, the gather_state function in the network module used synchronous state retrieval. This commit updates the function to use asynchronous state retrieval by leveraging the retrieve_async method provided by the nispor::NetState struct.

This change ensures that state retrieval does not block the main execution thread, improving the overall responsiveness of the application. Additionally, it paves the way for integrating asynchronous operations into other parts of the codebase.

### CODE REVIEW

**Comment by cathay4t** [comment]
@jona42-ui Do you still have interest on this? Otherwise, I would like to step in because I want to use `tokio/signal` to replace `ctrlc` which is blocking our compiling in Fedora.

**Comment by jona42-ui** [comment]
> @jona42-ui Do you still have interest on this? Otherwise, I would like to step in because I want to use `tokio/signal` to replace `ctrlc` which is blocking our compiling in Fedora.

its okay @cathay4t for now for you to step in. though I still have interest.

**Comment by cathay4t** [comment]
OK. I will let you know once PR created for this.

**Comment by cathay4t** [comment]
@jona42-ui Please check https://github.com/nmstate/nmstate/pull/2676 for my approach.

**Comment by cathay4t** [comment]
Closing in the favor of https://github.com/nmstate/nmstate/pull/2676

**Pull request closed without merging**
