### PR TITLE
CONTRIBUTING.md: Add compilation and installations steps

### PR DESCRIPTION
**Pull request by beekaz**

### CODE REVIEW

**Comment by ihuguet** [comment]
What is the right PR we are supposed to review. I was reviewing the other one...
Please cleanup as there are changes unrelated to the PR's subject in both PRs.

**Comment by beekaz** [comment]
> What is the right PR we are supposed to review. I was reviewing the other one... Please cleanup as there are changes unrelated to the PR's subject in both PRs.

here is the right one

> What is the right PR we are supposed to review. I was reviewing the other one... Please cleanup as there are changes unrelated to the PR's subject in both PRs.

This is the right pr to review but i dont know what exactly is wrong this CI / integ (fed-nm_stable-integ_tier1)  keeps failing  the error says error: failed to select a version for the requirement `nispor = "^1.2.18", i have tried locally to fix the dependency conflict yet

**Review by ihuguet — APPROVED** [review]

**Comment by ihuguet** [comment]
> This is the right pr to review but i dont know what exactly is wrong this CI / integ (fed-nm_stable-integ_tier1) keeps failing the error says error: failed to select a version for the requirement `nispor = "^1.2.18", i have tried locally to fix the dependency conflict yet

It's something that needs to be fixed in Fedora, it's not related to your changes so don't worry about it.

Approved.

**Comment by beekaz** [comment]
> > This is the right pr to review but i dont know what exactly is wrong this CI / integ (fed-nm_stable-integ_tier1) keeps failing the error says error: failed to select a version for the requirement `nispor = "^1.2.18", i have tried locally to fix the dependency conflict yet
> 
> It's something that needs to be fixed in Fedora, it's not related to your changes so don't worry about it.
> 
> Approved.

Alright thank you

**Comment by ffmancera** [comment]
This was finally done by: fe3e9eec027c17e4165bff1dfaceabef9f38ed73, closing it then. Thank you very much for your work.

**Pull request closed without merging**
