### PR TITLE
automation: Update docker image with NM fix

### PR DESCRIPTION
**Pull request by EdDev**
Adding NM fix for BZ#1642625.
It should be removed when the fix is available for Centos.

### CODE REVIEW

**Comment by EdDev** [comment]
I added it for my own reference, but I do not mind changing it. The image on docker hub is already with the updated version.
Waiting for your link/s (a repo will be preferred).

**Comment by tyll** [comment]
Here is my repo file: https://copr.fedorainfracloud.org/coprs/till/nmstate-NetworkManager/repo/epel-7/till-nmstate-NetworkManager-epel-7.repo

**Comment by tyll** [comment]
The RPM does not build because of failures in the tests: https://copr-be.cloud.fedoraproject.org/results/till/nmstate-NetworkManager/epel-7-x86_64/00816570-NetworkManager/build.log.gz

I sent an e-mail to the NM team to ask for help.

**Comment by tyll** [comment]
The package/repo is now ready

**Comment by EdDev** [comment]
ci test please

**Comment by EdDev** [comment]
ci test please

**Pull request merged**
