### PR TITLE
automation: Update vdsm tests container

### PR DESCRIPTION
**Pull request by almusil**
@ffmancera @cathay4t Please take a look

### CODE REVIEW

**Review by ffmancera — CHANGES_REQUESTED** [review]
Thanks for this contribution. Could you add the sign with -s? Thanks!

**Comment by almusil** [comment]
> Thanks for this contribution. Could you add the sign with -s? Thanks!

Done, will you handle the backports or should I walk through all branches with the old container reference? 
Thanks

**Comment by ffmancera** [comment]
> > Thanks for this contribution. Could you add the sign with -s? Thanks!
> 
> Done, will you handle the backports or should I walk through all branches with the old container reference? Thanks

I can handle the backports, no worries! Could you rebase the branch?

**Review by ffmancera — APPROVED** [review]
LGTM!

**Pull request merged**
