### PR TITLE
integration tests: Actually use a different prefix

### PR DESCRIPTION
**Pull request by tyll**

### CODE REVIEW

**Comment by tyll** [comment]
@EdDev stdci seems to take too long to report their status. :-/

**Comment by EdDev** [comment]
I think it did not trigger it (no links). Lets try to ask it nicely..

**Comment by EdDev** [comment]
ci test please

**Comment by EdDev** [comment]
It passed but the PR page was not updated: https://jenkins.ovirt.org/blue/organizations/jenkins/nmstate_nmstate_standard-check-pr/detail/nmstate_nmstate_standard-check-pr/273/pipeline/

**Comment by tyll** [comment]
Thank you. The page is there now AFAICS.

**Pull request merged**
