### PR TITLE
automation: compare packaging against nmstate-0.2 branch

### PR DESCRIPTION
**Pull request by ffmancera**
Signed-off-by: Fernando Fernandez Mancera <ffmancera@riseup.net>

### CODE REVIEW

**Comment by ffmancera** [comment]
I've tried to use git in order to get the branch that we are comparing to. But that seems impossible as it is a "github" thing. We could get the parent branch of the branch that we are trying to merge but that could break the function too in some cases.

**Comment by ffmancera** [comment]
This is needed for #887.

**Comment by ffmancera** [comment]
This is not working. The diff is complaning about `nmstate-0.2` does not exist.

**Comment by ffmancera** [comment]
This is working fine! :-)

**Comment by tyll** [comment]
Can you maybe use some travis variable and fallback to the hardcoded value if it is missing?
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables lists them. Candidates are TRAVIS_BRANCH, TRAVIS_PULL_REQUEST_BRANCH and TRAVIS_COMMIT_RANGE (maybe the range can be used for the diff instead of the branch names).

**Comment by ffmancera** [comment]
I am going to close this and moving this to #894.

**Pull request closed without merging**
