### PR TITLE
Replace sync API with async API

### PR DESCRIPTION
**Pull request by EjiroLaurelD**
Hello, my name is Ejiro, an outreachy applicant. I worked on issue #2580 replacing 
`nispor::NetState::retrieve_with_filter(&filter)` with 
 `nispor::NetState::retrieve_with_filter_async(&filter)`
 
 Please review. Thank you very much

### CODE REVIEW

**Review by cathay4t — CHANGES_REQUESTED** [review]
Simple text replacement will never works.

You do not have `await` or async executor.

Please investigate more on rust async and test your patch by:

```
cd rust
cargo build
cargo run show -k
```

**Comment by EjiroLaurelD** [comment]
> Simple text replacement will never works.
> 
> You do not have `await` or async executor.
> 
> Please investigate more on rust async and test your patch by:
> 
> ```
> cd rust
> cargo build
> cargo run show -k
> ```

Alright, I will investigate it. thank you

**Comment by cathay4t** [comment]
https://developers.redhat.com/articles/2023/10/26/how-consume-and-expose-rust-async-crates could help you understand how rust async works.

**Comment by EjiroLaurelD** [comment]
Hello @cathay4t I got this output after running `cargo build` and `cargo build show -k`
please review 
Screenshot 2024-03-13 195020

**Comment by EjiroLaurelD** [comment]
> Congratulations! One of the builds has completed. 🍾
> 
> You can install the built RPMs by following these steps:
> 
> * `sudo yum install -y dnf-plugins-core` on RHEL 8
> * `sudo dnf install -y dnf-plugins-core` on Fedora
> * `dnf copr enable packit/nmstate-nmstate-2582`
> * And now you can install the packages.
> 
> Please note that the RPMs should be used only in a testing environment.

@cathay4t can I use an ubuntu distro for this installation?

**Comment by cathay4t** [comment]
> > Congratulations! One of the builds has completed. 🍾
> > You can install the built RPMs by following these steps:
> > 
> > * `sudo yum install -y dnf-plugins-core` on RHEL 8
> > * `sudo dnf install -y dnf-plugins-core` on Fedora
> > * `dnf copr enable packit/nmstate-nmstate-2582`
> > * And now you can install the packages.
> > 
> > Please note that the RPMs should be used only in a testing environment.
> 
> @cathay4t can I use an ubuntu distro for this installation?

These copr tests is only for testing engineer. If you want to test your changes, `PREFIX=/usr make intall` will do the work on any distro including ubuntu

**Comment by EjiroLaurelD** [comment]
> > > Congratulations! One of the builds has completed. 🍾
> > > You can install the built RPMs by following these steps:
> > > 
> > > * `sudo yum install -y dnf-plugins-core` on RHEL 8
> > > * `sudo dnf install -y dnf-plugins-core` on Fedora
> > > * `dnf copr enable packit/nmstate-nmstate-2582`
> > > * And now you can install the packages.
> > > 
> > > Please note that the RPMs should be used only in a testing environment.
> > 
> > 
> > @cathay4t can I use an ubuntu distro for this installation?
> 
> These copr tests is only for testing engineer. If you want to test your changes, `PREFIX=/usr make intall` will do the work on any distro including ubuntu

Okay, I ran the command `PREFIX=/usr make intall`  and got this output. I am not sure what to make of it yet, but I do not see any errors. I am guessing that is good?
Screenshot 2024-03-20 104735

**Comment by jona42-ui** [comment]
@cathay4t @liangwen12year   are the build files generated as code changes meant to be committed upstream too?

**Comment by ffmancera** [comment]
Please, can you squash all the changes in a single commit?

**Comment by EjiroLaurelD** [comment]
> Please, can you squash all the changes in a single commit?

Done

**Comment by ffmancera** [comment]
Thank you for the contribution. We prefer to follow this approach https://github.com/nmstate/nmstate/pull/2635. Closing this, we encourage you to continue contributing and learning.

**Pull request closed without merging**
