### PR TITLE
Add sriov vlan protocol support

### PR DESCRIPTION
**Pull request by mlguerrero12**
These changes allow users to get and set the vlan protocol of sriov VFs.

Depends on https://github.com/nispor/nispor/pull/249

### CODE REVIEW

**Comment by mlguerrero12** [comment]
@cathay4t, could you please review this? 

The only part that I haven't addressed is when user sets the protocol 802.1ad with both vlan ID and QoS equal to zero. The driver (tested with mlx5 and ice) simply ignores this configuration. The problem is that the verification check of nmstate expects this to be applied but since this is ignored, the check fails.

(It works when either vlan id or qos is different than zero).

I'm not sure where to add this check (if protocol == 802.1ad && vlanid == 0 && qos ==0; return error). I was thinking to add it in gen_nm_vfs. What do you think?

**Comment by cathay4t** [comment]
The patch looks good. Let's wait nispor PR been merged.

**Comment by mlguerrero12** [comment]
```yml
interfaces:
- name: eno12409
  type: ethernet
  state: up
  mac-address: B4:96:91:C8:A5:21
  mtu: 1500
  min-mtu: 68
  max-mtu: 9702
  wait-ip: any
  ipv4:
    enabled: false
    dhcp: false
  ipv6:
    enabled: false
    dhcp: false
    autoconf: false
  accept-all-mac-addresses: false
  ethernet:
    sr-iov:
      total-vfs: 5
      vfs:
      - id: 0
        iface-name: eno12409v0
        mac-address: 0E:70:51:F8:CA:90
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 0
        qos: 0
        vlan-proto: 802.1q
      - id: 1
        iface-name: eno12409v1
        mac-address: 3A:FC:9B:FF:75:F6
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 100
        qos: 0
        vlan-proto: 802.1ad
      - id: 2
        iface-name: eno12409v2
        mac-address: 3A:31:B5:EB:4F:11
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 100
        qos: 0
        vlan-proto: 802.1q
      - id: 3
        iface-name: eno12409v3
        mac-address: C6:1D:3D:E5:04:8C
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 0
        qos: 0
        vlan-proto: 802.1q
      - id: 4
        iface-name: eno12409v4
        mac-address: F2:C5:7C:50:0F:97
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 0
        qos: 4
        vlan-proto: 802.1ad
    auto-negotiation: false
    speed: 25000
    duplex: full
```

**Comment by mlguerrero12** [comment]
changing protocol for VF 3 (see above)

[root@cnfdr28 nmstate]# nmstatectl apply desired_state.yaml 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:17Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z INFO  nmstate::nm::show] Got unsupported interface type generic: genev_sys_6081, ignoring
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface 10bb4482b3fff8e type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface 9708671fce74795 type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface genev_sys_6081 type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface a7ddd959c63fb12 type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface cfc6a7c3dd24a23 type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface ovn-k8s-mp0 type ovs-interface
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface 6b5ebe3f9280cc1 type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface 41a5228a4fe0d93 type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface br-int type ovs-interface
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface patch-br-int-to-br-ex_cnfdr28.telco5g.eng.rdu2.redhat.com type ovs-interface
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface 5df32e6762027bb type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface b59463957c839f2 type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface patch-br-ex_cnfdr28.telco5g.eng.rdu2.redhat.com-to-br-int type ovs-interface
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface 887dea325bc1a42 type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::ifaces::inter_ifaces] Ignoring interface d08467633df62cb type ethernet
[2023-12-11T09:54:18Z INFO  nmstate::query_apply::net_state] Created checkpoint /org/freedesktop/NetworkManager/Checkpoint/23
[2023-12-11T09:54:18Z INFO  nmstate::nm::query_apply::profile] Modifying connection UUID Some("7da2a114-34b4-4e7c-9276-5dbf3ba61b07"), ID Some("eno12409"), type Some("802-3-ethernet") name Some("eno12409")
[2023-12-11T09:54:18Z INFO  nmstate::nm::query_apply::profile] Reapplying connection 7da2a114-34b4-4e7c-9276-5dbf3ba61b07: eno12409/802-3-ethernet
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:18Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:18Z INFO  nmstate::nm::show] Got unsupported interface type generic: genev_sys_6081, ignoring
[2023-12-11T09:54:18Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eno12409.interface.ethernet.sr-iov.total-vfs desire '5', current '0'
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:19Z INFO  nmstate::nm::show] Got unsupported interface type generic: genev_sys_6081, ignoring
[2023-12-11T09:54:19Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eno12409.interface.ethernet.sr-iov.total-vfs desire '5', current '0'
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:20Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:20Z INFO  nmstate::nm::show] Got unsupported interface type generic: genev_sys_6081, ignoring
[2023-12-11T09:54:20Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eno12409.interface.ethernet.sr-iov.total-vfs desire '5', current '0'
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:21Z INFO  nmstate::nm::show] Got unsupported interface type generic: genev_sys_6081, ignoring
[2023-12-11T09:54:21Z INFO  nmstate::query_apply::net_state] Retrying on: SrIovVfNotFound: Failed to find VF 1 interface name of PF eno12409
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type geneve
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z WARN  nmstate::ovsdb::show] Unknown OVS interface type 
[2023-12-11T09:54:22Z INFO  nmstate::nm::show] Got unsupported interface type generic: genev_sys_6081, ignoring
[2023-12-11T09:54:22Z INFO  nmstate::query_apply::net_state] Destroyed checkpoint /org/freedesktop/NetworkManager/Checkpoint/23
dns-resolver: {}
route-rules: {}
routes: {}
interfaces:
- name: eno12409
  type: ethernet
  state: up
  mac-address: B4:96:91:C8:A5:21
  mtu: 1500
  min-mtu: 68
  max-mtu: 9702
  wait-ip: any
  ipv4:
    enabled: false
    dhcp: false
  ipv6:
    enabled: false
    dhcp: false
    autoconf: false
  accept-all-mac-addresses: false
  lldp:
    enabled: false
  ethtool:
    pause:
      rx: false
      tx: false
      autoneg: false
    feature:
      highdma: true
      hw-tc-offload: false
      loopback: false
      rx-checksum: true
      rx-gro: true
      rx-gro-list: false
      rx-hashing: true
      rx-ntuple-filter: true
      rx-udp-gro-forwarding: false
      rx-udp_tunnel-port-offload: true
      rx-vlan-filter: true
      rx-vlan-hw-parse: true
      rx-vlan-stag-filter: true
      rx-vlan-stag-hw-parse: false
      tx-checksum-ipv4: true
      tx-checksum-ipv6: true
      tx-checksum-sctp: true
      tx-generic-segmentation: true
      tx-gre-csum-segmentation: true
      tx-gre-segmentation: true
      tx-gso-partial: true
      tx-ipxip4-segmentation: true
      tx-ipxip6-segmentation: true
      tx-nocache-copy: false
      tx-tcp-ecn-segmentation: true
      tx-tcp-mangleid-segmentation: false
      tx-tcp-segmentation: true
      tx-tcp6-segmentation: true
      tx-udp-segmentation: true
      tx-udp_tnl-csum-segmentation: true
      tx-udp_tnl-segmentation: true
      tx-vlan-hw-insert: true
      tx-vlan-stag-hw-insert: false
    coalesce:
      adaptive-rx: true
      adaptive-tx: true
      rx-usecs: 50
      rx-usecs-high: 0
      tx-usecs: 50
    ring:
      rx: 2048
      rx-max: 8160
      tx: 256
      tx-max: 8160
  ethernet:
    sr-iov:
      total-vfs: 5
      vfs:
      - id: 0
        iface-name: eno12409v0
        mac-address: 0E:70:51:F8:CA:90
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 0
        qos: 0
        vlan-proto: 802.1q
      - id: 1
        iface-name: eno12409v1
        mac-address: 3A:FC:9B:FF:75:F6
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 100
        qos: 0
        vlan-proto: 802.1ad
      - id: 2
        iface-name: eno12409v2
        mac-address: 3A:31:B5:EB:4F:11
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 100
        qos: 0
        vlan-proto: 802.1q
      - id: 3
        iface-name: eno12409v3
        mac-address: C6:1D:3D:E5:04:8C
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 0
        qos: 3
        vlan-proto: 802.1ad
      - id: 4
        iface-name: eno12409v4
        mac-address: F2:C5:7C:50:0F:97
        spoof-check: true
        trust: false
        min-tx-rate: 0
        max-tx-rate: 0
        vlan-id: 0
        qos: 4
        vlan-proto: 802.1ad
    auto-negotiation: false
    speed: 25000
    duplex: full
ovs-db: {}
ovn: {}

**Comment by ihuguet** [comment]
> The only part that I haven't addressed is when user sets the protocol 802.1ad with both vlan ID and QoS equal to zero. The driver (tested with mlx5 and ice) simply ignores this configuration. The problem is that the verification check of nmstate expects this to be applied but since this is ignored, the check fails.
> 
> (It works when either vlan id or qos is different than zero).

This is not great for user experience. Should we preverify and reject this values before trying to apply them? I can't find any reason why vlan=0 && qos=0 should be invalid, so may it be considered as a bug in the drivers?

**Comment by mlguerrero12** [comment]
> > The only part that I haven't addressed is when user sets the protocol 802.1ad with both vlan ID and QoS equal to zero. The driver (tested with mlx5 and ice) simply ignores this configuration. The problem is that the verification check of nmstate expects this to be applied but since this is ignored, the check fails.
> > (It works when either vlan id or qos is different than zero).
> 
> This is not great for user experience. Should we preverify and reject this values before trying to apply them? I can't find any reason why vlan=0 && qos=0 should be invalid, so may it be considered as a bug in the drivers?

That's how drivers work and it makes sense, only when vlan or qos are different than zero, then it makes sense to set a vlan protocol. Otherwise, the frame is not tagged. We need to prevent this due to how nmstate works. We did the same for the sriov cni.

**Comment by mlguerrero12** [comment]
@cathay4t, @ihuguet, I added the check in sriov sanatize. Please have a look.

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
I have appended two patches:
 1. Add unit test for 802.1ad on VLAN 0 and QoS 0.
 2. Change python constant from `Ethernet.SRIOV.VFS.PROTO` to `Ethernet.SRIOV.VFS.VLAN_PROTO`. We need to be consistent between literal property name and constant variable name.

**Comment by cathay4t** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
