### PR TITLE
Dynamic: Use dhcp-iaid introduced in NM 1.22

### PR DESCRIPTION
**Pull request by almusil**
Use dhcp-iaid=mac for IPv4 and IPv6 dynamic address.

### CODE REVIEW

**Comment by almusil** [comment]
This cannot be merged before we move to NM 1.22

**Comment by EdDev** [comment]
Depends on #711

**Comment by EdDev** [comment]
> This would also mean that we cannot update Nmstate in Fedora 31 anymore unless we ask NM to also update there.

nmstate-0.1 is released on fc31, so we do not intend to have 0.2 there.
And I do not think we are interested in back-porting this (we cannot).

**Comment by tyll** [comment]
> > This would also mean that we cannot update Nmstate in Fedora 31 anymore unless we ask NM to also update there.
> 
> nmstate-0.1 is released on fc31, so we do not intend to have 0.2 there.

Ok, thank you for the clarification.

**Pull request merged**
