### PR TITLE
nm.bridge: Set only specified port options

### PR DESCRIPTION
**Pull request by tyll**
Signed-off-by: Till Maas <opensource@till.name>

### CODE REVIEW

**Comment by tyll** [comment]
This makes it possible to specify only a minimal state. However the state verification will fail because the port options are not canonicalized because it is a list of ports instead of a dict.

**Comment by tyll** [comment]
CI failed with `/usr/bin/docker-current: Get https://registry-1.docker.io/v2/nmstate/centos7-nmstate-dev/manifests/latest: received unexpected HTTP status: 503 Service Unavailable.` :-/

**Comment by tyll** [comment]
ci test please

**Comment by tyll** [comment]
vlan test failed...

**Comment by tyll** [comment]
ci test please

**Comment by cathay4t** [comment]
Merged. Thanks.

**Pull request merged**
